apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: account-svc
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: platform-deployments
spec:
  project: banking-platform
  source:
    repoURL: https://github.com/sanusi/banking-platform.git
    targetRevision: HEAD
    path: golang-banking-platform/deploy/helm/account-svc
    helm:
      valueFiles:
        - values.yaml
        - values-production.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: banking
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 5
