// Package postgres contains the PostgreSQL implementation of AuditRepository.
package postgres

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"time"

	"go.opentelemetry.io/otel/attribute"
	"gorm.io/gorm"

	"github.com/sanusi/banking/pkg/observability"
	"github.com/sanusi/banking/services/audit-svc/internal/domain/dao"
	"github.com/sanusi/banking/services/audit-svc/internal/domain/dto"
)

// ErrNotFound is returned when a requested audit event does not exist.
var ErrNotFound = errors.New("audit event not found")

// auditRepository implements repository.AuditRepository using GORM + PostgreSQL.
type auditRepository struct {
	tr *observability.ServiceTracer
	db *gorm.DB
}

// New creates a new PostgreSQL audit repository.
func New(db *gorm.DB) *auditRepository {
	return &auditRepository{
		tr: observability.NewServiceTracer("AuditRepository"),
		db: db,
	}
}

// Create inserts a new audit event. ID is auto-generated by PostgreSQL via
// gen_random_uuid() if not set.
func (r *auditRepository) Create(ctx context.Context, event *dao.AuditEvent) (err error) {
	ctx, span := r.tr.Start(ctx, "Create",
		attribute.String("audit.action", event.Action),
		attribute.String("audit.actor_id", event.ActorID),
	)
	defer r.tr.Finish(span, &err)

	if err = r.db.WithContext(ctx).Create(event).Error; err != nil {
		slog.ErrorContext(ctx, "audit repo: create event",
			slog.String("action", event.Action),
			slog.String("error", err.Error()),
		)
		return fmt.Errorf("create audit event: %w", err)
	}
	return nil
}

// GetByID retrieves a single event by UUID. Returns ErrNotFound if absent.
func (r *auditRepository) GetByID(ctx context.Context, id string) (event *dao.AuditEvent, err error) {
	ctx, span := r.tr.Start(ctx, "GetByID", attribute.String("audit.id", id))
	defer r.tr.Finish(span, &err)

	var e dao.AuditEvent
	if err = r.db.WithContext(ctx).Where("id = ?", id).First(&e).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, ErrNotFound
		}
		return nil, fmt.Errorf("get audit event: %w", err)
	}
	return &e, nil
}

// cursorPayload is what we encode/decode for keyset pagination.
type cursorPayload struct {
	CreatedAt time.Time `json:"t"`
	ID        string    `json:"i"`
}

// List applies filters and keyset pagination, returning events ordered by
// (created_at DESC, id DESC). Limit defaults to 50, max 200.
func (r *auditRepository) List(ctx context.Context, params dto.QueryParams) (events []*dao.AuditEvent, nextCursor string, err error) {
	ctx, span := r.tr.Start(ctx, "List")
	defer r.tr.Finish(span, &err)

	limit := params.Limit
	if limit <= 0 {
		limit = 50
	}
	if limit > 200 {
		limit = 200
	}

	q := r.db.WithContext(ctx).Model(&dao.AuditEvent{})

	// Apply equality filters
	if params.ActorID != "" {
		q = q.Where("actor_id = ?", params.ActorID)
	}
	if params.Action != "" {
		q = q.Where("action = ?", params.Action)
	}
	if params.Status != "" {
		q = q.Where("status = ?", params.Status)
	}
	if params.ServiceName != "" {
		q = q.Where("service_name = ?", params.ServiceName)
	}
	if params.TraceID != "" {
		q = q.Where("trace_id = ?", params.TraceID)
	}
	if params.Resource != "" {
		q = q.Where("resource = ?", params.Resource)
	}
	if params.ResourceID != "" {
		q = q.Where("resource_id = ?", params.ResourceID)
	}

	// Apply time range filters
	if params.From != nil {
		q = q.Where("created_at >= ?", params.From)
	}
	if params.To != nil {
		q = q.Where("created_at <= ?", params.To)
	}

	// Apply keyset cursor (created_at DESC, id DESC)
	if params.Cursor != "" {
		cp, decErr := decodeCursor(params.Cursor)
		if decErr == nil {
			q = q.Where("(created_at, id) < (?, ?)", cp.CreatedAt, cp.ID)
		}
	}

	// Fetch limit+1 to detect whether a next page exists
	var rows []*dao.AuditEvent
	if err = q.Order("created_at DESC, id DESC").Limit(limit + 1).Find(&rows).Error; err != nil {
		return nil, "", fmt.Errorf("list audit events: %w", err)
	}

	if len(rows) > limit {
		rows = rows[:limit]
		last := rows[len(rows)-1]
		nextCursor, _ = encodeCursor(cursorPayload{CreatedAt: last.CreatedAt, ID: last.ID})
	}

	return rows, nextCursor, nil
}

func encodeCursor(cp cursorPayload) (string, error) {
	b, err := json.Marshal(cp)
	if err != nil {
		return "", err
	}
	return base64.StdEncoding.EncodeToString(b), nil
}

func decodeCursor(cursor string) (cursorPayload, error) {
	b, err := base64.StdEncoding.DecodeString(cursor)
	if err != nil {
		return cursorPayload{}, err
	}
	var cp cursorPayload
	if err := json.Unmarshal(b, &cp); err != nil {
		return cursorPayload{}, err
	}
	return cp, nil
}
